# Generated by Django 4.1.4 on 2022-12-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Srudent',
            new_name='Student',
        ),
    ]
