# Generated by Django 4.1.4 on 2022-12-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0002_rename_srudent_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['number'], 'verbose_name_plural': 'Student_list'},
        ),
    ]
