# Generated by Django 4.1.4 on 2022-12-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_pic',
            field=models.ImageField(blank=True, null=True, upload_to='artists'),
        ),
    ]
