# Generated by Django 4.1.4 on 2022-12-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0003_rename_path_id_student_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
