# Generated by Django 4.1.5 on 2023-01-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Purchases', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sales', 'verbose_name_plural': 'Sales'},
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='price_total',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
    ]
