# Generated by Django 4.1.5 on 2023-01-31 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_purchases_options_alter_sales_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='price_total',
        ),
    ]
