# Generated by Django 4.1.5 on 2023-01-31 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_purchases_price_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='price_total',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
