# Generated by Django 4.1.5 on 2023-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_purchases_price_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
