# Generated by Django 4.1.5 on 2023-02-01 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_sales_price_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='firm',
            name='image',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='stock.product'),
        ),
    ]
