# Generated by Django 4.1.5 on 2023-02-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_brand_image_firm_image_product_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
