# Generated by Django 4.1.4 on 2022-12-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0003_alter_student_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='student_files'),
        ),
    ]
