# Generated by Django 4.1.4 on 2022-12-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="path",
            new_name="path_id",
        ),
    ]
