# Generated by Django 4.1.4 on 2022-12-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_api", "0002_rename_path_student_path_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="path_id",
            new_name="path",
        ),
    ]
